// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvkkddpjydtrjvokckcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2a2tkZHBqeWR0cmp2b2tja2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjA0NTAsImV4cCI6MjA2MzM5NjQ1MH0.CFWlvika99DmWs2bwRL18wYa3deL6wRyH0JsxuBueP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);